server:
  port: 28080

spring:
  datasource:
    url: jdbc:mysql://192.168.3.129/master?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  cache:
    type: redis
  redis:
    host: 192.168.3.195
    port: 6379       

keycloak:
  ribbon:
    listOfServers: http://192.168.3.129:8080
  admin:
    username: admin
    password: admin
  
elastic:
  cluster:
    name: docker-cluster
  host: 192.168.3.195
  port: 9300
