server:
  port: 28080

spring:
  datasource:
    url: jdbc:mysql://localhost/master?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  cache:
    type: redis
  redis:
    host: 192.168.3.129
    port: 63799       

keycloak:
  ribbon:
    listOfServers: http://localhost:8080
  admin:
    username: admin
    password: admin
  
